export const pokemonCopy = {
  eyebrow: 'Explora',
  title: 'Pokedex',
  searchPlaceholder: 'Buscar Pókemon...',
  filters: 'Filtros',
  loadMore: 'Ver más',
  showingCount: (shown: number, total: number) => `Mostrando ${shown} de ${total} Pokémon`,
  emptyTitle: 'No encontramos Pokémon',
  emptyDescription: 'Prueba con otro nombre o quita algunos filtros para ampliar la búsqueda.',
  clearSearch: 'Limpiar búsqueda',
  errorTitle: 'Algo salió mal...',
  errorDescription:
    'No pudimos cargar la información en este momento. Verifica tu conexión o intenta nuevamente más tarde.',
  loadMoreError: 'No pudimos cargar más Pokémon. Verifica tu conexión.',
  retry: 'Reintentar',
  clearFilters: 'Borrar filtros',
  filtersModalTitle: 'Filtra por tus preferencias',
  filtersSectionType: 'Tipo',
  apply: 'Aplicar',
  cancel: 'Cancelar',
  backToList: 'Volver al listado',
  weight: 'PESO',
  height: 'ALTURA',
  category: 'CATEGORÍA',
  ability: 'HABILIDAD',
  gender: 'GÉNERO',
  weaknesses: 'Debilidades',
  share: 'Compartir',
  shareCopied: '¡Copiado!',
  shareFailed: 'No se pudo copiar',
  addFavorite: 'Agregar a favoritos',
  removeFavorite: 'Quitar de favoritos',
} as const
